/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: burunduk (https://sketchfab.com/burunduk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-court-028a4d52159940b7a248e859f1c1ac07
Title: Basketball court
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Basketball = (props) => {
  const { nodes, materials } = useGLTF("/basketball_court.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[1440.842, -0.001, -9753.692]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box14969_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box14969_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[2080.202, -22.191, -9198.915]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_008_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_008_L_blue_0.geometry}
            material={materials.L_blue}
          />
        </group>
        <group
          position={[1222.906, -0.001, -9750.05]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15550_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15550_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[1657.071, -0.001, -9752.754]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15551_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15551_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[1972.43, -0.001, -9168.319]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15553_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15553_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[1760.972, -0.001, -9156.238]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15554_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15554_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[1549.375, -0.001, -9165.295]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15555_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15555_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[1328.944, -0.001, -9162.859]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15556_brown_0.geometry}
            material={materials.brown}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box15556_metal_0.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[2080.202, -22.191, -9739.572]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_009_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_009_L_blue_0.geometry}
            material={materials.L_blue}
          />
        </group>
        <group
          position={[1024.876, -22.191, -9739.573]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_010_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_010_L_blue_0.geometry}
            material={materials.L_blue}
          />
        </group>
        <group
          position={[1024.876, -22.191, -9198.916]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_011_metal_0.geometry}
            material={materials.metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.street_light_011_L_blue_0.geometry}
            material={materials.L_blue}
          />
        </group>
        <group
          position={[1995.229, -0.001, -9465.018]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object283_black_0.geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object283_red_0.geometry}
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object283_gray_0.geometry}
            material={materials.gray}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object283_white_0.geometry}
            material={materials.white}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object283_glass_0.geometry}
            material={materials.glass}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GeoSphere014_orange_0.geometry}
          material={materials.orange}
          position={[1845.741, 24.486, -9382.354]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box14954_metal_0.geometry}
          material={materials.metal}
          position={[1152.304, 100, -9066.914]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box14890_dirt_0.geometry}
          material={materials.dirt}
          position={[1552.305, -40, -9463.915]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle004_white_0.geometry}
          material={materials.white}
          position={[1553.374, 0.5, -9463.807]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box14976_red_0.geometry}
          material={materials.material}
          position={[1928.534, 0, -9467.904]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15533_metal_0.geometry}
          material={materials.metal}
          position={[1352.304, 100, -9066.914]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15534_metal_0.geometry}
          material={materials.metal}
          position={[1552.304, 100, -9066.915]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15535_metal_0.geometry}
          material={materials.metal}
          position={[1752.306, 100, -9066.915]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15536_metal_0.geometry}
          material={materials.metal}
          position={[1952.306, 100, -9066.915]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15537_metal_0.geometry}
          material={materials.metal}
          position={[1952.304, 99.762, -9860.916]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15538_metal_0.geometry}
          material={materials.metal}
          position={[1152.303, 100, -9860.916]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15539_metal_0.geometry}
          material={materials.metal}
          position={[1352.303, 99.999, -9860.916]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15540_metal_0.geometry}
          material={materials.metal}
          position={[1552.303, 100, -9860.916]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15541_metal_0.geometry}
          material={materials.metal}
          position={[1752.304, 100, -9860.916]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15542_metal_0.geometry}
          material={materials.metal}
          position={[2056.614, 99.761, -9165.226]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15543_metal_0.geometry}
          material={materials.metal}
          position={[2056.613, 99.761, -9365.226]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15544_metal_0.geometry}
          material={materials.metal}
          position={[2056.613, 99.761, -9565.225]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15545_metal_0.geometry}
          material={materials.metal}
          position={[2056.613, 99.761, -9765.225]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15546_metal_0.geometry}
          material={materials.metal}
          position={[1047.995, 100, -9165.226]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15547_metal_0.geometry}
          material={materials.metal}
          position={[1047.994, 100, -9365.226]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15548_metal_0.geometry}
          material={materials.metal}
          position={[1047.994, 100, -9565.225]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box15549_metal_0.geometry}
          material={materials.metal}
          position={[1047.994, 100, -9765.225]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane1292_blue_0.geometry}
          material={materials.blue}
          position={[1551.799, 0, -9473.059]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/basketball_court.glb");

export default Basketball;
